export const mockPatient = {
  id: "pt-0042",
  name: "Sarah Chen",
  age: 34,
  dob: "1990-08-14",
  gender: "Female",
  phone: "+1 (415) 882-3371",
  email: "s.chen@email.com",
  healthLiteracyLevel: "medium" as const,
  anxietyLevel: "moderate" as const,
  preferredLanguage: "English",
  lastVisit: "2025-11-03",
  nextAppointment: "2026-04-20",
  insuranceProvider: "Delta Dental PPO",
  avatar: "SC",
  healthHistory: [
    "Type 2 Diabetes (controlled)",
    "Mild acid reflux",
  ],
  medications: ["Metformin 500mg", "Omeprazole 20mg"],
  allergies: ["Penicillin"],
};

export const mockHealthScore = {
  overall: 67,
  trend: [52, 58, 61, 65, 67],
  trendDates: ["Nov", "Dec", "Jan", "Feb", "Mar"],
  dimensions: [
    { label: "Periodontal Health", score: 58, weight: 0.25, icon: "gum" },
    { label: "Restorative Status", score: 72, weight: 0.20, icon: "tooth" },
    { label: "Hygiene Indicators", score: 80, weight: 0.20, icon: "brush" },
    { label: "Structural Integrity", score: 65, weight: 0.15, icon: "shield" },
    { label: "Bite & Occlusion", score: 70, weight: 0.10, icon: "scan" },
    { label: "Soft Tissue Health", score: 55, weight: 0.10, icon: "heart" },
  ],
  tier: "Fair",
  projectedScore: 79,
  projectionNote: "Completing the current treatment plan could bring your score to 79",
};

export const mockDiagnoses = [
  {
    id: "dx-001",
    condition: "Interproximal Caries",
    plainEnglishName: "Cavity Between Teeth",
    toothIds: ["#14", "#15"],
    severity: "moderate" as const,
    location: "Mesial surface of upper left first molar",
    dentistConfidence: 0.91,
    aiConfidence: 0.87,
    combinedConfidence: 0.90,
    urgency: "soon" as const,
    reversibility: "irreversible" as const,
    ifUntreated: "The decay will expand deeper into the dentin, potentially reaching the pulp and requiring a root canal within 6–12 months.",
    aiExplanation: "You have a small cavity forming between two of your upper back teeth. Think of it like a tiny hole that's slowly getting bigger — right now it's in the outer layer of your tooth, which means a simple filling can stop it completely.",
    linkedScans: ["scan-001"],
  },
  {
    id: "dx-002",
    condition: "Generalized Mild Periodontitis",
    plainEnglishName: "Early Gum Disease",
    toothIds: ["#24", "#25", "#26", "#27"],
    severity: "mild" as const,
    location: "Posterior mandibular region, bilateral",
    dentistConfidence: 0.84,
    aiConfidence: 0.79,
    combinedConfidence: 0.82,
    urgency: "routine" as const,
    reversibility: "reversible" as const,
    ifUntreated: "Without treatment, bone loss may progress and teeth can become loose over 2–5 years.",
    aiExplanation: "Your gums are showing early signs of inflammation and the bone around your lower back teeth has started to recede slightly. The good news: at this stage, a thorough professional cleaning and improved daily flossing can reverse most of this.",
    linkedScans: ["scan-002"],
  },
  {
    id: "dx-003",
    condition: "Dentinal Hypersensitivity",
    plainEnglishName: "Tooth Sensitivity",
    toothIds: ["#6", "#7", "#8"],
    severity: "mild" as const,
    location: "Anterior maxillary, cervical region",
    dentistConfidence: 0.76,
    aiConfidence: 0.68,
    combinedConfidence: 0.73,
    urgency: "routine" as const,
    reversibility: "reversible" as const,
    ifUntreated: "Sensitivity may worsen with continued enamel erosion, likely related to acid reflux.",
    aiExplanation: "The protective enamel on your front teeth has worn thinner than ideal, exposing tiny tubules that lead to the nerve — that's what causes the sharp sensation with cold or sweet foods.",
    linkedScans: ["scan-001"],
  },
];

export const mockTreatmentPlan = {
  totalDuration: "4–5 months",
  phases: [
    {
      id: "phase-1",
      order: 1,
      title: "Stabilization",
      subtitle: "Stop the active decay",
      dateRange: "Apr – May 2026",
      isCompleted: false,
      isActive: true,
      treatments: [
        {
          id: "tx-001",
          name: "Composite Restoration",
          plainEnglishName: "White Filling",
          category: "restorative",
          appointments: 1,
          durationMinutes: 60,
          steps: [
            "Numbing injection — mild pinch, then numbness",
            "Decay removed with precise drill",
            "Tooth shaped and cleaned",
            "Composite resin applied in thin layers",
            "Cured with blue light, bite checked",
          ],
          painLevel: "minimal",
          recoveryDays: 0,
          longevity: "8–12 years",
          costRange: "$180–$250",
          insuranceCovered: true,
          isUrgent: true,
        },
        {
          id: "tx-002",
          name: "Full Mouth Debridement",
          plainEnglishName: "Deep Cleaning",
          category: "periodontal",
          appointments: 2,
          durationMinutes: 90,
          steps: [
            "Ultrasonic scaler removes buildup above gumline",
            "Hand instruments clean below gumline",
            "Antimicrobial rinse applied",
            "Home care instructions provided",
          ],
          painLevel: "mild",
          recoveryDays: 2,
          longevity: "Ongoing with maintenance",
          costRange: "$280–$420",
          insuranceCovered: true,
          isUrgent: false,
        },
      ],
    },
    {
      id: "phase-2",
      order: 2,
      title: "Restoration",
      subtitle: "Repair & protect",
      dateRange: "May – Jun 2026",
      isCompleted: false,
      isActive: false,
      treatments: [
        {
          id: "tx-003",
          name: "Desensitization Treatment",
          plainEnglishName: "Sensitivity Relief",
          category: "preventive",
          appointments: 1,
          durationMinutes: 45,
          steps: [
            "Fluoride varnish applied to exposed areas",
            "Bonding agent seals dentinal tubules",
            "Custom prescription toothpaste recommended",
          ],
          painLevel: "none",
          recoveryDays: 0,
          longevity: "6–12 months per treatment",
          costRange: "$90–$140",
          insuranceCovered: false,
          isUrgent: false,
        },
      ],
    },
    {
      id: "phase-3",
      order: 3,
      title: "Maintenance",
      subtitle: "Monitor & sustain",
      dateRange: "Aug 2026 onward",
      isCompleted: false,
      isActive: false,
      isOptional: false,
      treatments: [
        {
          id: "tx-004",
          name: "Periodontal Maintenance",
          plainEnglishName: "Gum Health Check",
          category: "preventive",
          appointments: 4,
          durationMinutes: 60,
          steps: [
            "Probing depths measured and recorded",
            "Plaque index scored",
            "Targeted cleaning",
            "Fluoride treatment",
          ],
          painLevel: "none",
          recoveryDays: 0,
          longevity: "Every 3 months",
          costRange: "$140–$180",
          insuranceCovered: true,
          isUrgent: false,
        },
      ],
    },
  ],
};

export const mockScanAnnotations = [
  { id: "a1", x: 38, y: 28, label: "Early caries #14", severity: "concern", width: 12, height: 10 },
  { id: "a2", x: 55, y: 32, label: "Bone level reduced", severity: "watch", width: 18, height: 8 },
  { id: "a3", x: 22, y: 48, label: "Healthy restoration", severity: "note", width: 10, height: 10 },
];
